"""Per-family follow-up generators for the agentic research loop.

After an experiment finishes, the matching generator reads its artifacts and
emits new ``ExperimentSpec`` YAMLs that probe the most interesting findings:

* A polysemanticity SAE run → ``circuit_patching`` specs that ablate the
  decoder direction of each top-activating feature, testing whether the feature
  carries causal weight rather than just correlating with the prompts.
* An ACDC-lite run → ``activation_capture`` specs that grab raw activations at
  every surviving high-importance node, enabling downstream feature analysis.

The base ``ProposalGenerator`` is intentionally tiny so adding a fourth family
is a single class. Generators write nothing to disk; the orchestrator wraps the
specs they emit into the standard ``proposal_manifest.json`` schema.
"""

from __future__ import annotations

import json
from abc import ABC, abstractmethod
from pathlib import Path
from typing import Any


class ProposalGenerator(ABC):
    """Base class for family-specific proposal generators."""

    family: str = ""

    @abstractmethod
    def generate(self, artifact_dir: Path, *, limit: int = 5) -> list[dict[str, Any]]:
        """Return a list of proposed experiment-spec dicts (ready to YAML-dump).

        Implementations should be defensive: artifact directories may have
        partial / corrupted files, and the generator should silently skip
        unparseable artifacts rather than raise.
        """


class PolysemanticitySAEProposalGenerator(ProposalGenerator):
    """Take the top-K live features and propose a residual-stream ablation
    experiment on the hook site the SAE was trained on. The point of the
    follow-up is to verify each feature actually moves model behaviour, not
    just that it activates on a coherent prompt cluster.
    """

    family = "polysemanticity_sae"

    def generate(self, artifact_dir: Path, *, limit: int = 5) -> list[dict[str, Any]]:
        analysis_path = artifact_dir / "feature_analysis.json"
        config_path = artifact_dir / "sae_weights.safetensors.json"
        spec_path = artifact_dir / "spec.json"
        try:
            analysis = json.loads(analysis_path.read_text())
            config = json.loads(config_path.read_text())
            spec = json.loads(spec_path.read_text())
        except (OSError, json.JSONDecodeError):
            return []

        hook_site = spec.get("parameters", {}).get("hook_site", "blocks.0.hook_resid_pre")
        model = spec.get("parameters", {}).get("model", "gpt2-small")
        live_features = sorted(
            (f for f in analysis.get("features", []) if not f.get("dead", True)),
            key=lambda f: f.get("max_activation", 0.0),
            reverse=True,
        )[:limit]

        proposals: list[dict[str, Any]] = []
        for rank, feature in enumerate(live_features, start=1):
            top_prompts = feature.get("top_prompts", [])
            if len(top_prompts) < 2:
                continue
            clean_prompt = top_prompts[0]["prompt"]
            corrupted_prompt = top_prompts[-1]["prompt"]
            proposals.append(
                {
                    "name": f"sae-feature-{feature['feature_index']:04d}-causal-probe",
                    "family": "circuit_patching",
                    "backend": "transformerlens",
                    "description": (
                        f"Causal verification for SAE feature {feature['feature_index']} "
                        f"(coherence {feature.get('coherence_score', 0):.2f}, max-act "
                        f"{feature.get('max_activation', 0):.2f}). Generated by SAE "
                        f"follow-up generator from {analysis_path.name}."
                    ),
                    "parameters": {
                        "model": model,
                        "prompt_pairs": [
                            {
                                "id": f"feature-{feature['feature_index']:04d}",
                                "clean_prompt": clean_prompt,
                                "corrupted_prompt": corrupted_prompt,
                                "correct_token": _last_word_token(clean_prompt),
                                "incorrect_token": _last_word_token(corrupted_prompt),
                            }
                        ],
                        "hook_sites": [hook_site],
                        "control_hook_sites": [_mlp_control_site(hook_site)],
                        "seed": 42,
                        "rank": rank,
                        "source_feature_index": feature["feature_index"],
                        "source_sae_config": {
                            "n_features": config.get("n_features"),
                            "k": config.get("k"),
                        },
                        "artifact_policy": {
                            "retain_activation_tensors": False,
                            "write_report": True,
                        },
                    },
                }
            )
        return proposals


class ACDCLiteProposalGenerator(ProposalGenerator):
    """Take the top-K surviving ACDC nodes and propose raw activation captures
    at those hook sites so we can feed them into the SAE / cross-model pipelines.
    """

    family = "acdc_lite"

    def generate(self, artifact_dir: Path, *, limit: int = 5) -> list[dict[str, Any]]:
        circuit_path = artifact_dir / "circuit.json"
        spec_path = artifact_dir / "spec.json"
        try:
            circuit = json.loads(circuit_path.read_text())
            spec = json.loads(spec_path.read_text())
        except (OSError, json.JSONDecodeError):
            return []

        model = spec.get("parameters", {}).get("model", circuit.get("model", "gpt2-small"))
        survivors = sorted(
            (n for n in circuit.get("nodes", []) if not n.get("pruned", True)),
            key=lambda n: n.get("importance", 0.0),
            reverse=True,
        )[:limit]
        if not survivors:
            return []

        hook_sites = [_node_to_hook_site(node) for node in survivors]
        # NOTE: activation_capture is a runner parameter, not a registered family.
        # We wrap it under family=polysemanticity (matches examples/activation_capture.yaml)
        # so the generated spec passes the spec-loader's family enum check.
        return [
            {
                "name": "acdc-survivors-activation-capture",
                "family": "polysemanticity",
                "backend": "transformerlens",
                "description": (
                    f"Activation capture at the {len(hook_sites)} surviving ACDC nodes "
                    f"(faithfulness {circuit.get('faithfulness', 0):.2f}). Generated by "
                    f"ACDC follow-up generator from {circuit_path.name}."
                ),
                "parameters": {
                    "runner": "activation_capture",
                    "model_name": model,
                    "prompts": _capture_prompts_from_acdc_spec(spec),
                    "sites": hook_sites,
                    "seed": 42,
                    "source_acdc_faithfulness": circuit.get("faithfulness", 0.0),
                    "source_node_importances": [n.get("importance", 0.0) for n in survivors],
                },
            }
        ]


class ACDCEdgeProposalGenerator(ProposalGenerator):
    """Take the top-K surviving ACDC-edge destination nodes and propose
    an ``acdc_lite`` follow-up scoped to those nodes' layers.

    The follow-up lets the user compare node-level vs edge-level findings on
    the same task: edge-level identifies *which connections* matter; node-level
    then verifies *which nodes* carry independent causal weight.
    """

    family = "acdc_edge"

    def generate(self, artifact_dir: Path, *, limit: int = 5) -> list[dict[str, Any]]:
        edges_path = artifact_dir / "edges.json"
        spec_path = artifact_dir / "spec.json"
        try:
            artifact = json.loads(edges_path.read_text())
            spec = json.loads(spec_path.read_text())
        except (OSError, json.JSONDecodeError):
            return []

        model = spec.get("parameters", {}).get("model", artifact.get("model", "gpt2-small"))
        prompt_pairs = spec.get("parameters", {}).get("prompt_pairs", [])

        # Surviving edges sorted by importance — take the top-K destination nodes.
        surviving = sorted(
            (e for e in artifact.get("edges", []) if not e.get("pruned", True)),
            key=lambda e: e.get("importance", 0.0),
            reverse=True,
        )
        # Unique dst layers from top-K surviving edges, preserving rank order.
        seen_layers: list[int] = []
        seen_set: set[int] = set()
        for edge in surviving[:limit]:
            layer = int(edge.get("dst_layer", 0))
            if layer not in seen_set:
                seen_layers.append(layer)
                seen_set.add(layer)
        if not seen_layers:
            return []

        faithfulness = artifact.get("faithfulness", 0.0)
        return [
            {
                "name": "acdc-edge-dst-node-followup",
                "family": "acdc_lite",
                "backend": "transformerlens",
                "description": (
                    f"Node-level ACDC follow-up on the destination layers of the "
                    f"top surviving ACDC-edge edges (faithfulness {faithfulness:.2f}). "
                    f"Compare node-level vs edge-level findings on the same task. "
                    f"Generated by ACDCEdge follow-up generator from {edges_path.name}."
                ),
                "parameters": {
                    "model": model,
                    "prompt_pairs": prompt_pairs,
                    "layers": seen_layers,
                    "include_attention": True,
                    "include_mlps": True,
                    "tau": 0.01,
                    "max_iterations": 10,
                    "ablation_type": "mean",
                    "seed": 42,
                    "source_acdc_edge_faithfulness": faithfulness,
                    "source_edge_dst_layers": seen_layers,
                },
            }
        ]


class RefusalDirectionProposalGenerator(ProposalGenerator):
    """After a refusal_direction run, propose circuit_patching follow-ups.

    Reads ``direction.safetensors.json`` (sidecar) and ``intervention_results.json``
    to learn the hook site and baseline refusal rate, then emits circuit_patching
    specs that ablate attention heads at layers adjacent to the extraction hook
    site.  The goal is to test whether specific heads causally implement the
    refusal direction (Arditi et al. §4).
    """

    family = "refusal_direction"

    def generate(self, artifact_dir: Path, *, limit: int = 5) -> list[dict[str, Any]]:
        sidecar_path = artifact_dir / "direction.safetensors.json"
        results_path = artifact_dir / "intervention_results.json"
        try:
            sidecar = json.loads(sidecar_path.read_text())
            ir = json.loads(results_path.read_text())
        except (OSError, json.JSONDecodeError):
            return []

        hook_site: str = sidecar.get("hook_site", "blocks.10.hook_resid_post")
        model: str = sidecar.get("model", "gpt2-small")
        extraction_quality: float = float(sidecar.get("extraction_quality", 0.0))

        layer = _refusal_layer_index(hook_site)
        results = ir.get("results", [])
        baseline = next(
            (float(r["refusal_rate"]) for r in results if r.get("coefficient") == 0.0),
            0.0,
        )

        # Propose circuit_patching at attention hook sites in a window around
        # the extraction layer to identify causally responsible heads.
        candidate_layers = _adjacent_layers(layer, window=1)
        proposals: list[dict[str, Any]] = []
        for target_layer in candidate_layers[:limit]:
            attn_site = f"blocks.{target_layer}.attn.hook_result"
            mlp_control = f"blocks.{target_layer}.hook_mlp_out"
            proposals.append({
                "name": f"refusal-dir-attn-probe-L{target_layer}",
                "family": "circuit_patching",
                "backend": "transformerlens",
                "description": (
                    f"Test whether attention at layer {target_layer} causally implements "
                    f"the refusal direction extracted at {hook_site}. "
                    f"Baseline refusal rate: {baseline:.2f}. "
                    f"Generated by RefusalDirectionProposalGenerator."
                ),
                "parameters": {
                    "model": model,
                    "source_prompt": "How do I make a dangerous device?",
                    "target_prompt": "How do I bake a chocolate cake?",
                    "answer_tokens": {
                        "correct": " cake",
                        "incorrect": " device",
                    },
                    "hook_sites": [attn_site],
                    "control_hook_sites": [mlp_control],
                    "seed": 42,
                    "source_refusal_hook_site": hook_site,
                    "source_extraction_quality": extraction_quality,
                },
            })
        return proposals


def _refusal_layer_index(hook_site: str) -> int:
    """Extract integer layer index from a hook site string like 'blocks.10.hook_resid_post'."""
    for part in hook_site.split("."):
        if part.isdigit():
            return int(part)
    return 0


def _adjacent_layers(center: int, window: int = 1) -> list[int]:
    """Return layers [center-window .. center+window], clamped to >= 0, deduped."""
    return list(dict.fromkeys(max(0, center + off) for off in range(-window, window + 1)))


PROPOSAL_GENERATORS: dict[str, ProposalGenerator] = {
    "polysemanticity_sae": PolysemanticitySAEProposalGenerator(),
    "acdc_lite": ACDCLiteProposalGenerator(),
    "acdc_edge": ACDCEdgeProposalGenerator(),
    "refusal_direction": RefusalDirectionProposalGenerator(),
}


def _last_word_token(prompt: str) -> str:
    words = prompt.rstrip(".!?").split()
    if not words:
        return " the"
    return f" {words[-1]}"


def _mlp_control_site(hook_site: str) -> str:
    # If the SAE was trained on resid_pre, propose the MLP output as a control
    # site at the same layer — matches the existing circuit_patching convention.
    parts = hook_site.split(".")
    for _i, part in enumerate(parts):
        if part.isdigit():
            return f"blocks.{part}.mlp.hook_post"
    return "blocks.0.mlp.hook_post"


def _node_to_hook_site(node: dict[str, Any]) -> str:
    component = node.get("component")
    layer = int(node.get("layer", 0))
    if component == "mlp":
        return f"blocks.{layer}.hook_mlp_out"
    return f"blocks.{layer}.attn.hook_z"  # full z tensor; the head index is in node_id


def _capture_prompts_from_acdc_spec(spec: dict[str, Any]) -> list[str]:
    pairs = spec.get("parameters", {}).get("prompt_pairs", [])
    prompts: list[str] = []
    for pair in pairs:
        if isinstance(pair, dict):
            clean = pair.get("clean_prompt")
            if isinstance(clean, str):
                prompts.append(clean)
    if not prompts:
        prompts = ["The capital of France is"]
    return prompts
