"""Per-family follow-up generators for the agentic research loop.

After an experiment finishes, the matching generator reads its artifacts and
emits new ``ExperimentSpec`` YAMLs that probe the most interesting findings:

* A polysemanticity SAE run → ``circuit_patching`` specs that ablate the
  decoder direction of each top-activating feature, testing whether the feature
  carries causal weight rather than just correlating with the prompts.
* An ACDC-lite run → ``activation_capture`` specs that grab raw activations at
  every surviving high-importance node, enabling downstream feature analysis.

The base ``ProposalGenerator`` is intentionally tiny so adding a fourth family
is a single class. Generators write nothing to disk; the orchestrator wraps the
specs they emit into the standard ``proposal_manifest.json`` schema.
"""

from __future__ import annotations

import json
from abc import ABC, abstractmethod
from pathlib import Path
from typing import Any


class ProposalGenerator(ABC):
    """Base class for family-specific proposal generators."""

    family: str = ""

    @abstractmethod
    def generate(self, artifact_dir: Path, *, limit: int = 5) -> list[dict[str, Any]]:
        """Return a list of proposed experiment-spec dicts (ready to YAML-dump).

        Implementations should be defensive: artifact directories may have
        partial / corrupted files, and the generator should silently skip
        unparseable artifacts rather than raise.
        """


class PolysemanticitySAEProposalGenerator(ProposalGenerator):
    """Take the top-K live features and propose a residual-stream ablation
    experiment on the hook site the SAE was trained on. The point of the
    follow-up is to verify each feature actually moves model behaviour, not
    just that it activates on a coherent prompt cluster.
    """

    family = "polysemanticity_sae"

    def generate(self, artifact_dir: Path, *, limit: int = 5) -> list[dict[str, Any]]:
        analysis_path = artifact_dir / "feature_analysis.json"
        config_path = artifact_dir / "sae_weights.safetensors.json"
        spec_path = artifact_dir / "spec.json"
        try:
            analysis = json.loads(analysis_path.read_text())
            config = json.loads(config_path.read_text())
            spec = json.loads(spec_path.read_text())
        except (OSError, json.JSONDecodeError):
            return []

        hook_site = spec.get("parameters", {}).get("hook_site", "blocks.0.hook_resid_pre")
        model = spec.get("parameters", {}).get("model", "gpt2-small")
        live_features = sorted(
            (f for f in analysis.get("features", []) if not f.get("dead", True)),
            key=lambda f: f.get("max_activation", 0.0),
            reverse=True,
        )[:limit]

        proposals: list[dict[str, Any]] = []
        for rank, feature in enumerate(live_features, start=1):
            top_prompts = feature.get("top_prompts", [])
            if len(top_prompts) < 2:
                continue
            clean_prompt = top_prompts[0]["prompt"]
            corrupted_prompt = top_prompts[-1]["prompt"]
            proposals.append(
                {
                    "name": f"sae-feature-{feature['feature_index']:04d}-causal-probe",
                    "family": "circuit_patching",
                    "backend": "transformerlens",
                    "description": (
                        f"Causal verification for SAE feature {feature['feature_index']} "
                        f"(coherence {feature.get('coherence_score', 0):.2f}, max-act "
                        f"{feature.get('max_activation', 0):.2f}). Generated by SAE "
                        f"follow-up generator from {analysis_path.name}."
                    ),
                    "parameters": {
                        "model": model,
                        "prompt_pairs": [
                            {
                                "id": f"feature-{feature['feature_index']:04d}",
                                "clean_prompt": clean_prompt,
                                "corrupted_prompt": corrupted_prompt,
                                "correct_token": _last_word_token(clean_prompt),
                                "incorrect_token": _last_word_token(corrupted_prompt),
                            }
                        ],
                        "hook_sites": [hook_site],
                        "control_hook_sites": [_mlp_control_site(hook_site)],
                        "seed": 42,
                        "rank": rank,
                        "source_feature_index": feature["feature_index"],
                        "source_sae_config": {
                            "n_features": config.get("n_features"),
                            "k": config.get("k"),
                        },
                        "artifact_policy": {
                            "retain_activation_tensors": False,
                            "write_report": True,
                        },
                    },
                }
            )
        return proposals


class ACDCLiteProposalGenerator(ProposalGenerator):
    """Take the top-K surviving ACDC nodes and propose raw activation captures
    at those hook sites so we can feed them into the SAE / cross-model pipelines.
    """

    family = "acdc_lite"

    def generate(self, artifact_dir: Path, *, limit: int = 5) -> list[dict[str, Any]]:
        circuit_path = artifact_dir / "circuit.json"
        spec_path = artifact_dir / "spec.json"
        try:
            circuit = json.loads(circuit_path.read_text())
            spec = json.loads(spec_path.read_text())
        except (OSError, json.JSONDecodeError):
            return []

        model = spec.get("parameters", {}).get("model", circuit.get("model", "gpt2-small"))
        survivors = sorted(
            (n for n in circuit.get("nodes", []) if not n.get("pruned", True)),
            key=lambda n: n.get("importance", 0.0),
            reverse=True,
        )[:limit]
        if not survivors:
            return []

        hook_sites = [_node_to_hook_site(node) for node in survivors]
        # NOTE: activation_capture is a runner parameter, not a registered family.
        # We wrap it under family=polysemanticity (matches examples/activation_capture.yaml)
        # so the generated spec passes the spec-loader's family enum check.
        return [
            {
                "name": "acdc-survivors-activation-capture",
                "family": "polysemanticity",
                "backend": "transformerlens",
                "description": (
                    f"Activation capture at the {len(hook_sites)} surviving ACDC nodes "
                    f"(faithfulness {circuit.get('faithfulness', 0):.2f}). Generated by "
                    f"ACDC follow-up generator from {circuit_path.name}."
                ),
                "parameters": {
                    "runner": "activation_capture",
                    "model_name": model,
                    "prompts": _capture_prompts_from_acdc_spec(spec),
                    "sites": hook_sites,
                    "seed": 42,
                    "source_acdc_faithfulness": circuit.get("faithfulness", 0.0),
                    "source_node_importances": [n.get("importance", 0.0) for n in survivors],
                },
            }
        ]


class ACDCEdgeProposalGenerator(ProposalGenerator):
    """Take the top-K surviving ACDC-edge destination nodes and propose
    an ``acdc_lite`` follow-up scoped to those nodes' layers.

    The follow-up lets the user compare node-level vs edge-level findings on
    the same task: edge-level identifies *which connections* matter; node-level
    then verifies *which nodes* carry independent causal weight.
    """

    family = "acdc_edge"

    def generate(self, artifact_dir: Path, *, limit: int = 5) -> list[dict[str, Any]]:
        edges_path = artifact_dir / "edges.json"
        spec_path = artifact_dir / "spec.json"
        try:
            artifact = json.loads(edges_path.read_text())
            spec = json.loads(spec_path.read_text())
        except (OSError, json.JSONDecodeError):
            return []

        model = spec.get("parameters", {}).get("model", artifact.get("model", "gpt2-small"))
        prompt_pairs = spec.get("parameters", {}).get("prompt_pairs", [])

        # Surviving edges sorted by importance — take the top-K destination nodes.
        surviving = sorted(
            (e for e in artifact.get("edges", []) if not e.get("pruned", True)),
            key=lambda e: e.get("importance", 0.0),
            reverse=True,
        )
        # Unique dst layers from top-K surviving edges, preserving rank order.
        seen_layers: list[int] = []
        seen_set: set[int] = set()
        for edge in surviving[:limit]:
            layer = int(edge.get("dst_layer", 0))
            if layer not in seen_set:
                seen_layers.append(layer)
                seen_set.add(layer)
        if not seen_layers:
            return []

        faithfulness = artifact.get("faithfulness", 0.0)
        return [
            {
                "name": "acdc-edge-dst-node-followup",
                "family": "acdc_lite",
                "backend": "transformerlens",
                "description": (
                    f"Node-level ACDC follow-up on the destination layers of the "
                    f"top surviving ACDC-edge edges (faithfulness {faithfulness:.2f}). "
                    f"Compare node-level vs edge-level findings on the same task. "
                    f"Generated by ACDCEdge follow-up generator from {edges_path.name}."
                ),
                "parameters": {
                    "model": model,
                    "prompt_pairs": prompt_pairs,
                    "layers": seen_layers,
                    "include_attention": True,
                    "include_mlps": True,
                    "tau": 0.01,
                    "max_iterations": 10,
                    "ablation_type": "mean",
                    "seed": 42,
                    "source_acdc_edge_faithfulness": faithfulness,
                    "source_edge_dst_layers": seen_layers,
                },
            }
        ]


class RefusalDirectionProposalGenerator(ProposalGenerator):
    """After a refusal_direction run, propose circuit_patching follow-ups.

    Reads ``direction.safetensors.json`` (sidecar) and ``intervention_results.json``
    to learn the hook site and baseline refusal rate, then emits circuit_patching
    specs that ablate attention heads at layers adjacent to the extraction hook
    site.  The goal is to test whether specific heads causally implement the
    refusal direction (Arditi et al. §4).
    """

    family = "refusal_direction"

    def generate(self, artifact_dir: Path, *, limit: int = 5) -> list[dict[str, Any]]:
        sidecar_path = artifact_dir / "direction.safetensors.json"
        results_path = artifact_dir / "intervention_results.json"
        try:
            sidecar = json.loads(sidecar_path.read_text())
            ir = json.loads(results_path.read_text())
        except (OSError, json.JSONDecodeError):
            return []

        hook_site: str = sidecar.get("hook_site", "blocks.10.hook_resid_post")
        model: str = sidecar.get("model", "gpt2-small")
        extraction_quality: float = float(sidecar.get("extraction_quality", 0.0))

        layer = _refusal_layer_index(hook_site)
        results = ir.get("results", [])
        baseline = next(
            (float(r["refusal_rate"]) for r in results if r.get("coefficient") == 0.0),
            0.0,
        )

        # Propose circuit_patching at attention hook sites in a window around
        # the extraction layer to identify causally responsible heads.
        candidate_layers = _adjacent_layers(layer, window=1)
        proposals: list[dict[str, Any]] = []
        for target_layer in candidate_layers[:limit]:
            attn_site = f"blocks.{target_layer}.attn.hook_result"
            mlp_control = f"blocks.{target_layer}.hook_mlp_out"
            proposals.append({
                "name": f"refusal-dir-attn-probe-L{target_layer}",
                "family": "circuit_patching",
                "backend": "transformerlens",
                "description": (
                    f"Test whether attention at layer {target_layer} causally implements "
                    f"the refusal direction extracted at {hook_site}. "
                    f"Baseline refusal rate: {baseline:.2f}. "
                    f"Generated by RefusalDirectionProposalGenerator."
                ),
                "parameters": {
                    "model": model,
                    "source_prompt": "How do I make a dangerous device?",
                    "target_prompt": "How do I bake a chocolate cake?",
                    "answer_tokens": {
                        "correct": " cake",
                        "incorrect": " device",
                    },
                    "hook_sites": [attn_site],
                    "control_hook_sites": [mlp_control],
                    "seed": 42,
                    "source_refusal_hook_site": hook_site,
                    "source_extraction_quality": extraction_quality,
                },
            })
        return proposals


def _refusal_layer_index(hook_site: str) -> int:
    """Extract integer layer index from a hook site string like 'blocks.10.hook_resid_post'."""
    for part in hook_site.split("."):
        if part.isdigit():
            return int(part)
    return 0


def _adjacent_layers(center: int, window: int = 1) -> list[int]:
    """Return layers [center-window .. center+window], clamped to >= 0, deduped."""
    return list(dict.fromkeys(max(0, center + off) for off in range(-window, window + 1)))


class SAECrossModelProposalGenerator(ProposalGenerator):
    """After a sae_cross_model run, propose per-feature ``activation_capture``
    probes for the top-N matched feature pairs.

    For each high-cosine matched pair we emit a circuit_patching spec that
    ablates the source decoder direction, verifying whether the conserved
    feature is causally active in the source model.
    """

    family = "sae_cross_model"

    def generate(self, artifact_dir: Path, *, limit: int = 5) -> list[dict[str, Any]]:
        matched_path = artifact_dir / "matched_features.json"
        summary_path = artifact_dir / "match_summary.json"
        spec_path = artifact_dir / "spec.json"
        try:
            matched = json.loads(matched_path.read_text())
            summary = json.loads(summary_path.read_text())
            spec = json.loads(spec_path.read_text())
        except (OSError, json.JSONDecodeError):
            return []

        hook_site: str = summary.get("hook_site", "blocks.4.hook_resid_pre")
        source_model: str = summary.get(
            "source_model", spec.get("parameters", {}).get("source_model", "gpt2")
        )
        high_threshold: float = float(summary.get("high_similarity_threshold", 0.8))

        top_pairs = [m for m in matched if float(m.get("cosine", 0.0)) >= high_threshold][:limit]
        if not top_pairs:
            # Fall back to top-N by cosine regardless of threshold
            top_pairs = sorted(
                matched, key=lambda m: float(m.get("cosine", 0.0)), reverse=True
            )[:limit]

        proposals: list[dict[str, Any]] = []
        for pair in top_pairs:
            src_feat = pair.get("source_feature", 0)
            tgt_feat = pair.get("target_feature", 0)
            cosine = float(pair.get("cosine", 0.0))
            src_prompts = pair.get("source_top_prompts", [])
            if len(src_prompts) < 2:
                continue
            clean_prompt = src_prompts[0]
            corrupted_prompt = src_prompts[-1]
            proposals.append(
                {
                    "name": (
                        f"sae-cross-model-src{src_feat:04d}-tgt{tgt_feat:04d}-causal-probe"
                    ),
                    "family": "circuit_patching",
                    "backend": "transformerlens",
                    "description": (
                        f"Causal probe for conserved SAE feature pair "
                        f"(src={src_feat}, tgt={tgt_feat}, cosine={cosine:.3f}). "
                        f"Tests whether the source decoder direction at {hook_site} "
                        f"is causally active, not merely correlated. "
                        f"Generated by SAECrossModelProposalGenerator."
                    ),
                    "parameters": {
                        "model": source_model,
                        "prompt_pairs": [
                            {
                                "id": f"src-feat-{src_feat:04d}",
                                "clean_prompt": clean_prompt,
                                "corrupted_prompt": corrupted_prompt,
                                "correct_token": _last_word_token(clean_prompt),
                                "incorrect_token": _last_word_token(corrupted_prompt),
                            }
                        ],
                        "hook_sites": [hook_site],
                        "control_hook_sites": [_mlp_control_site(hook_site)],
                        "seed": 42,
                        "source_feature_pair": {
                            "source_feature": src_feat,
                            "target_feature": tgt_feat,
                            "cosine": cosine,
                        },
                        "artifact_policy": {
                            "retain_activation_tensors": False,
                            "write_report": True,
                        },
                    },
                }
            )
        return proposals


class AttributionPatchingProposalGenerator(ProposalGenerator):
    """After an attribution_patching run, propose exact circuit_patching on the top-K sites.

    This is the canonical two-phase workflow:
      1. Cheap attribution scan (1 fwd + 1 bwd pass, all sites simultaneously).
      2. Expensive exact patching on the top-K attribution sites to confirm causal weight.
    """

    family = "attribution_patching"

    def generate(self, artifact_dir: Path, *, limit: int = 5) -> list[dict[str, Any]]:
        summary_path = artifact_dir / "attribution_summary.json"
        ranked_path = artifact_dir / "attribution_ranked.json"
        spec_path = artifact_dir / "spec.json"
        try:
            summary = json.loads(summary_path.read_text())
            ranked = json.loads(ranked_path.read_text())
            spec = json.loads(spec_path.read_text())
        except (OSError, json.JSONDecodeError):
            return []

        model: str = summary.get("model", spec.get("parameters", {}).get("model", "gpt2-small"))
        prompt_pairs: list[dict[str, Any]] = spec.get("parameters", {}).get("prompt_pairs", [])
        if not prompt_pairs:
            return []

        top_sites = [row["hook_site"] for row in ranked[:limit] if "hook_site" in row]
        if not top_sites:
            return []

        return [
            {
                "name": "attribution-followup-exact-patching",
                "family": "circuit_patching",
                "backend": "transformerlens",
                "description": (
                    f"Exact activation patching on the top-{len(top_sites)} sites "
                    f"identified by attribution patching scan "
                    f"(mean |attribution| = "
                    f"{summary.get('mean_abs_attribution', 0.0):.6f}). "
                    "Generated by AttributionPatchingProposalGenerator. "
                    "Attribution is a first-order approximation; exact patching confirms "
                    "causal weight."
                ),
                "parameters": {
                    "model": model,
                    "prompt_pairs": prompt_pairs,
                    "hook_sites": top_sites,
                    "seed": 42,
                    "source_attribution_top_sites": top_sites,
                    "artifact_policy": {
                        "retain_activation_tensors": False,
                        "write_report": True,
                    },
                },
            }
        ]


class CrosscoderProposalGenerator(ProposalGenerator):
    """After a crosscoder run, propose circuit_patching on the top divergent features.

    Divergent features (high |model_score|) are model-specific and therefore
    prime candidates for causal probing: ablating their decoder directions in
    each model separately should produce differential behavioural effects.
    """

    family = "crosscoder"

    def generate(self, artifact_dir: Path, *, limit: int = 5) -> list[dict[str, Any]]:
        divergent_path = artifact_dir / "divergent_features.json"
        spec_path = artifact_dir / "spec.json"
        try:
            divergent = json.loads(divergent_path.read_text())
            spec = json.loads(spec_path.read_text())
        except (OSError, json.JSONDecodeError):
            return []

        params = spec.get("parameters", {})
        source_model: str = divergent.get("source_model", params.get("source_model", "gpt2"))
        target_model: str = divergent.get("target_model", params.get("target_model", "distilgpt2"))
        hook_site: str = params.get("hook_site", "blocks.5.hook_resid_post")
        top_features: list[dict[str, Any]] = divergent.get("divergent_features", [])[:limit]

        proposals: list[dict[str, Any]] = []
        for feature in top_features:
            feature_idx = feature.get("feature_index", 0)
            model_score = float(feature.get("model_score", 0.0))
            top_prompts = feature.get("top_prompts", [])
            if len(top_prompts) < 2:
                continue
            clean_prompt = top_prompts[0]["prompt"]
            corrupted_prompt = top_prompts[-1]["prompt"]
            # Test on the model where this feature is dominant
            # (source if score<0, target if score>0)
            primary_model = source_model if model_score < 0 else target_model
            proposals.append(
                {
                    "name": (
                        f"crosscoder-feature-{feature_idx:04d}-causal-probe"
                        f"-{'src' if model_score < 0 else 'tgt'}"
                    ),
                    "family": "circuit_patching",
                    "backend": "transformerlens",
                    "description": (
                        f"Causal probe of crosscoder feature {feature_idx} "
                        f"(model_score={model_score:.3f}) on {primary_model} at "
                        f"'{hook_site}'. Generated by CrosscoderProposalGenerator."
                    ),
                    "parameters": {
                        "model": primary_model,
                        "hook_sites": [hook_site],
                        "prompt_pairs": [
                            {
                                "clean_prompt": clean_prompt,
                                "corrupted_prompt": corrupted_prompt,
                            }
                        ],
                        "seed": 42,
                        "crosscoder_feature_index": feature_idx,
                        "crosscoder_model_score": model_score,
                    },
                }
            )
        return proposals


class DirectLogitAttributionProposalGenerator(ProposalGenerator):
    """After a DLA run, propose circuit_patching on the top-3 positive components.

    The top positive components (highest logit contribution toward the correct
    token) are natural candidates for causal verification: DLA is correlational,
    patching checks whether they are truly necessary.
    """

    family = "direct_logit_attribution"

    def generate(self, artifact_dir: Path, *, limit: int = 5) -> list[dict[str, Any]]:
        summary_path = artifact_dir / "lda_summary.json"
        spec_path = artifact_dir / "spec.json"
        try:
            summary = json.loads(summary_path.read_text())
            spec = json.loads(spec_path.read_text())
        except (OSError, json.JSONDecodeError):
            return []

        model = spec.get("parameters", {}).get("model", "gpt2-small")
        prompt_pairs = spec.get("parameters", {}).get("prompt_pairs", [])
        top_positive = summary.get("top_positive", [])[:3]
        if not top_positive or not prompt_pairs:
            return []

        hook_sites: list[str] = []
        for comp in top_positive:
            ctype = comp.get("component_type")
            layer = comp.get("layer")
            head = comp.get("head")
            if layer is None:
                continue
            if ctype == "attn_head" and head is not None:
                hook_sites.append(f"blocks.{layer}.attn.hook_result")
            elif ctype == "mlp":
                hook_sites.append(f"blocks.{layer}.hook_mlp_out")

        # Deduplicate preserving order
        seen: set[str] = set()
        unique_sites = [s for s in hook_sites if not (s in seen or seen.add(s))]  # type: ignore[func-returns-value]
        if not unique_sites:
            return []

        proposals: list[dict[str, Any]] = []
        for pair in prompt_pairs[:limit]:
            if not isinstance(pair, dict):
                continue
            proposals.append(
                {
                    "name": f"dla-top-causal-probe-{pair.get('id', 'pair')}",
                    "family": "circuit_patching",
                    "backend": "transformerlens",
                    "description": (
                        f"Causal verification for top DLA components "
                        f"{[c['component_id'] for c in top_positive]}. "
                        f"Generated by DirectLogitAttributionProposalGenerator."
                    ),
                    "parameters": {
                        "model": model,
                        "prompt_pairs": [pair],
                        "hook_sites": unique_sites[:3],
                        "seed": 42,
                        "source_dla_top_components": [
                            c["component_id"] for c in top_positive
                        ],
                    },
                }
            )
        return proposals[:limit]


class SparseProbingProposalGenerator(ProposalGenerator):
    """After a sparse_probing run, propose direct_logit_attribution to check
    whether the probe direction shows up in unembed-projected contributions.

    If the probe found a sparse concept direction, DLA can show which components
    write along that direction at the final token position.
    """

    family = "sparse_probing"

    def generate(self, artifact_dir: Path, *, limit: int = 5) -> list[dict[str, Any]]:
        summary_path = artifact_dir / "probe_summary.json"
        spec_path = artifact_dir / "spec.json"
        try:
            summary = json.loads(summary_path.read_text())
            spec = json.loads(spec_path.read_text())
        except (OSError, json.JSONDecodeError):
            return []

        model = summary.get("model", spec.get("parameters", {}).get("model", "gpt2-small"))
        eval_accuracy = float(summary.get("eval_accuracy", 0.0))
        if eval_accuracy < 0.6:
            return []

        positive_prompts = spec.get("parameters", {}).get("positive_prompts", [])
        negative_prompts = spec.get("parameters", {}).get("negative_prompts", [])
        if not positive_prompts or not negative_prompts:
            return []

        neg_anchor = negative_prompts[0]
        pairs = []
        for i, pos in enumerate(positive_prompts[:limit]):
            pairs.append(
                {
                    "id": f"probe-pair-{i:04d}",
                    "clean_prompt": pos,
                    "corrupted_prompt": neg_anchor,
                    "correct_token": _last_word_token(pos),
                    "incorrect_token": _last_word_token(neg_anchor),
                }
            )

        return [
            {
                "name": "sparse-probe-dla-followup",
                "family": "direct_logit_attribution",
                "backend": "transformerlens",
                "description": (
                    f"DLA follow-up for sparse probe at {summary.get('hook_site')} "
                    f"(eval_acc={eval_accuracy:.3f}, "
                    f"nonzero={summary.get('nonzero_count')}/{summary.get('total_count')}). "
                    f"Checks whether probe direction appears in unembed contributions. "
                    f"Generated by SparseProbingProposalGenerator."
                ),
                "parameters": {
                    "model": model,
                    "prompt_pairs": pairs,
                    "seed": 42,
                    "source_probe_hook_site": summary.get("hook_site"),
                    "source_probe_eval_accuracy": eval_accuracy,
                    "source_probe_nonzero_count": summary.get("nonzero_count"),
                },
            }
        ]


class CausalScrubbingProposalGenerator(ProposalGenerator):
    """After a causal_scrubbing run, propose circuit_patching follow-ups.

    If scrubbed faithfulness is LOW (< 0.5) the circuit is incomplete.  We
    propose ``circuit_patching`` on every hook site *adjacent* to the protected
    set (one layer before the earliest protected layer and one layer after the
    latest) so the researcher can find what's missing.
    """

    family = "causal_scrubbing"

    def generate(self, artifact_dir: Path, *, limit: int = 5) -> list[dict[str, Any]]:
        summary_path = artifact_dir / "scrubbing_summary.json"
        spec_path = artifact_dir / "spec.json"
        try:
            summary = json.loads(summary_path.read_text())
            spec = json.loads(spec_path.read_text())
        except (OSError, json.JSONDecodeError):
            return []

        faithfulness: float = float(summary.get("scrubbed_faithfulness", 1.0))
        if faithfulness >= 0.5:
            # Hypothesis is adequately supported — no follow-up needed.
            return []

        model: str = summary.get("model", spec.get("parameters", {}).get("model", "gpt2-small"))
        protected_sites: list[str] = summary.get("protected_sites", [])
        prompts: list[dict[str, Any]] = spec.get("parameters", {}).get("prompts", [])
        if not prompts:
            return []

        # Derive layer indices from protected site names and build adjacent sites.
        layers = _layers_from_sites(protected_sites)
        candidate_layers = _adjacent_layers_for_scrubbing(layers, window=1)[:limit]
        if not candidate_layers:
            return []

        # Build a minimal clean/corrupted pair from the first two prompts.
        if len(prompts) < 2:
            return []
        clean_prompt: str = prompts[0].get("prompt", "")
        corrupted_prompt: str = prompts[1].get("prompt", "")
        if not clean_prompt or not corrupted_prompt:
            return []

        proposals: list[dict[str, Any]] = []
        for layer in candidate_layers:
            attn_site = f"blocks.{layer}.attn.hook_z"
            mlp_site = f"blocks.{layer}.hook_mlp_out"
            proposals.append(
                {
                    "name": f"scrubbing-gap-probe-L{layer}",
                    "family": "circuit_patching",
                    "backend": "transformerlens",
                    "description": (
                        f"Circuit patching at layer {layer} to find the component missing "
                        f"from the causal scrubbing hypothesis (faithfulness={faithfulness:.3f}). "
                        f"Adjacent to protected sites: {protected_sites}. "
                        f"Generated by CausalScrubbingProposalGenerator."
                    ),
                    "parameters": {
                        "model": model,
                        "prompt_pairs": [
                            {
                                "id": f"scrub-gap-L{layer}",
                                "clean_prompt": clean_prompt,
                                "corrupted_prompt": corrupted_prompt,
                                "correct_token": _last_word_token(clean_prompt),
                                "incorrect_token": _last_word_token(corrupted_prompt),
                            }
                        ],
                        "hook_sites": [attn_site],
                        "control_hook_sites": [mlp_site],
                        "seed": 42,
                        "source_scrubbing_faithfulness": faithfulness,
                        "source_protected_sites": protected_sites,
                        "artifact_policy": {
                            "retain_activation_tensors": False,
                            "write_report": True,
                        },
                    },
                }
            )
        return proposals


def _layers_from_sites(sites: list[str]) -> list[int]:
    """Extract unique integer layer indices from TransformerLens hook site names."""
    layers: list[int] = []
    seen: set[int] = set()
    for site in sites:
        for part in site.split("."):
            if part.isdigit():
                layer = int(part)
                if layer not in seen:
                    layers.append(layer)
                    seen.add(layer)
                break
    return sorted(layers)


def _adjacent_layers_for_scrubbing(layers: list[int], window: int = 1) -> list[int]:
    """Return layers just outside the protected set (before min and after max)."""
    if not layers:
        return []
    candidates = []
    min_layer = layers[0]
    max_layer = layers[-1]
    for off in range(1, window + 1):
        if min_layer - off >= 0:
            candidates.append(min_layer - off)
        candidates.append(max_layer + off)
    return list(dict.fromkeys(candidates))


class LogitLensProposalGenerator(ProposalGenerator):
    """After a logit_lens run, propose circuit_patching at the 'decision layer'.

    The decision layer is where the rank-of-correct transitions from >10 to <3
    in the mean-rank-by-layer curve.  At that layer, something in the residual
    stream resolves the answer; exact patching can identify the causal component.
    """

    family = "logit_lens"

    def generate(self, artifact_dir: Path, *, limit: int = 5) -> list[dict[str, Any]]:
        summary_path = artifact_dir / "lens_summary.json"
        results_path = artifact_dir / "lens_results.json"
        spec_path = artifact_dir / "spec.json"
        try:
            summary = json.loads(summary_path.read_text())
            results = json.loads(results_path.read_text())
            spec = json.loads(spec_path.read_text())
        except (OSError, json.JSONDecodeError):
            return []

        model = spec.get("parameters", {}).get("model", "gpt2-small")
        mean_rank: list[float] = summary.get("mean_rank_by_layer", [])
        if len(mean_rank) < 2:
            return []

        # Find the first layer where rank crosses from >10 to <3
        decision_layer: int | None = None
        for L in range(1, len(mean_rank)):
            if mean_rank[L - 1] > 10 and mean_rank[L] < 3:
                decision_layer = L
                break
        # Fallback: first layer where rank < 3
        if decision_layer is None:
            for L, rank in enumerate(mean_rank):
                if rank < 3:
                    decision_layer = L
                    break
        if decision_layer is None:
            return []

        # Build prompt_pairs from lens results
        prompt_pairs: list[dict[str, Any]] = []
        for pr in results:
            if not isinstance(pr, dict):
                continue
            correct_token = pr.get("correct_token", "")
            incorrect_token = pr.get("incorrect_token", "")
            if not incorrect_token:
                continue
            prompt_pairs.append(
                {
                    "id": pr.get("id", "") or pr.get("prompt", "")[:40],
                    "clean_prompt": pr.get("prompt", ""),
                    "corrupted_prompt": pr.get("prompt", ""),  # same prompt, different token
                    "correct_token": correct_token,
                    "incorrect_token": incorrect_token,
                }
            )
        if not prompt_pairs:
            return []

        attn_site = f"blocks.{decision_layer}.attn.hook_result"
        mlp_site = f"blocks.{decision_layer}.hook_mlp_out"

        proposals: list[dict[str, Any]] = []
        for hook_site, label in [(attn_site, "attn"), (mlp_site, "mlp")]:
            proposals.append(
                {
                    "name": f"lens-decision-L{decision_layer}-{label}-probe",
                    "family": "circuit_patching",
                    "backend": "transformerlens",
                    "description": (
                        f"Circuit patching at decision layer {decision_layer} "
                        f"({label}) where logit-lens rank-of-correct transitions "
                        f"from >{10} to <3. Verifies causal weight of this layer. "
                        f"Generated by LogitLensProposalGenerator."
                    ),
                    "parameters": {
                        "model": model,
                        "prompt_pairs": prompt_pairs[:limit],
                        "hook_sites": [hook_site],
                        "control_hook_sites": [mlp_site if label == "attn" else attn_site],
                        "seed": 42,
                        "source_logit_lens_decision_layer": decision_layer,
                        "source_logit_lens_rank_before": mean_rank[decision_layer - 1],
                        "source_logit_lens_rank_after": mean_rank[decision_layer],
                    },
                }
            )
        return proposals[:limit]


class CAASteeringProposalGenerator(ProposalGenerator):
    """After a caa_steering run, propose circuit_patching at the most effective layer.

    Reads ``layer_effectiveness.json`` to find the layer with the largest
    refusal-rate shift under steering, then emits circuit_patching specs that
    ablate attention heads at that layer to find which heads / MLP modules
    causally implement the steering direction.
    """

    family = "caa_steering"

    def generate(self, artifact_dir: Path, *, limit: int = 5) -> list[dict[str, Any]]:
        eff_path = artifact_dir / "layer_effectiveness.json"
        spec_path = artifact_dir / "spec.json"
        try:
            eff = json.loads(eff_path.read_text())
            spec = json.loads(spec_path.read_text())
        except (OSError, json.JSONDecodeError):
            return []

        model: str = eff.get("model", spec.get("parameters", {}).get("model", "gpt2-small"))
        hook_site_template: str = eff.get(
            "hook_site_template", "blocks.{L}.hook_resid_post"
        )
        layers_data: dict[str, Any] = eff.get("layers", {})
        if not layers_data:
            return []

        # Find the layer with the highest best_refusal_rate_shift.
        best_layer_str = max(
            layers_data,
            key=lambda k: float(layers_data[k].get("best_refusal_rate_shift", 0.0)),
        )
        best_layer = int(best_layer_str)
        best_eff = layers_data[best_layer_str]
        extraction_quality = float(best_eff.get("extraction_quality", 0.0))
        best_shift = float(best_eff.get("best_refusal_rate_shift", 0.0))
        best_coeff = float(best_eff.get("best_coefficient", 1.0))

        proposals: list[dict[str, Any]] = []
        proposals.append({
            "name": f"caa-steering-attn-probe-L{best_layer}",
            "family": "circuit_patching",
            "backend": "transformerlens",
            "description": (
                f"Test whether attention at layer {best_layer} causally implements "
                f"the CAA steering direction (best refusal-rate shift={best_shift:.2f}, "
                f"best coeff={best_coeff:+.1f}, extraction quality={extraction_quality:.3f}). "
                f"Hook site template: {hook_site_template}. "
                f"Generated by CAASteeringProposalGenerator."
            ),
            "parameters": {
                "model": model,
                "source_prompt": "How do I make a dangerous device?",
                "target_prompt": "How do I bake a chocolate cake?",
                "answer_tokens": {"correct": " cake", "incorrect": " device"},
                "hook_sites": [f"blocks.{best_layer}.attn.hook_result"],
                "control_hook_sites": [f"blocks.{best_layer}.hook_mlp_out"],
                "seed": 42,
                "source_caa_best_layer": best_layer,
                "source_caa_extraction_quality": extraction_quality,
                "source_caa_best_refusal_rate_shift": best_shift,
            },
        })

        # Secondary proposals at remaining layers, ranked by effectiveness.
        remaining = sorted(
            ((k, v) for k, v in layers_data.items() if k != best_layer_str),
            key=lambda kv: float(kv[1].get("best_refusal_rate_shift", 0.0)),
            reverse=True,
        )
        for k, v in remaining[: limit - 1]:
            layer2 = int(k)
            proposals.append({
                "name": f"caa-steering-attn-probe-L{layer2}",
                "family": "circuit_patching",
                "backend": "transformerlens",
                "description": (
                    f"Circuit patching at layer {layer2} "
                    f"(refusal-rate shift={v.get('best_refusal_rate_shift', 0):.2f}). "
                    f"Generated by CAASteeringProposalGenerator."
                ),
                "parameters": {
                    "model": model,
                    "source_prompt": "How do I make a dangerous device?",
                    "target_prompt": "How do I bake a chocolate cake?",
                    "answer_tokens": {"correct": " cake", "incorrect": " device"},
                    "hook_sites": [f"blocks.{layer2}.attn.hook_result"],
                    "control_hook_sites": [f"blocks.{layer2}.hook_mlp_out"],
                    "seed": 42,
                    "source_caa_layer": layer2,
                },
            })

        return proposals[:limit]


PROPOSAL_GENERATORS: dict[str, ProposalGenerator] = {
    "polysemanticity_sae": PolysemanticitySAEProposalGenerator(),
    "acdc_lite": ACDCLiteProposalGenerator(),
    "acdc_edge": ACDCEdgeProposalGenerator(),
    "refusal_direction": RefusalDirectionProposalGenerator(),
    "sae_cross_model": SAECrossModelProposalGenerator(),
    "attribution_patching": AttributionPatchingProposalGenerator(),
    "crosscoder": CrosscoderProposalGenerator(),
    "direct_logit_attribution": DirectLogitAttributionProposalGenerator(),
    "sparse_probing": SparseProbingProposalGenerator(),
    "causal_scrubbing": CausalScrubbingProposalGenerator(),
    "logit_lens": LogitLensProposalGenerator(),
    "caa_steering": CAASteeringProposalGenerator(),
}


def _last_word_token(prompt: str) -> str:
    words = prompt.rstrip(".!?").split()
    if not words:
        return " the"
    return f" {words[-1]}"


def _mlp_control_site(hook_site: str) -> str:
    # If the SAE was trained on resid_pre, propose the MLP output as a control
    # site at the same layer — matches the existing circuit_patching convention.
    parts = hook_site.split(".")
    for _i, part in enumerate(parts):
        if part.isdigit():
            return f"blocks.{part}.mlp.hook_post"
    return "blocks.0.mlp.hook_post"


def _node_to_hook_site(node: dict[str, Any]) -> str:
    component = node.get("component")
    layer = int(node.get("layer", 0))
    if component == "mlp":
        return f"blocks.{layer}.hook_mlp_out"
    return f"blocks.{layer}.attn.hook_z"  # full z tensor; the head index is in node_id


def _capture_prompts_from_acdc_spec(spec: dict[str, Any]) -> list[str]:
    pairs = spec.get("parameters", {}).get("prompt_pairs", [])
    prompts: list[str] = []
    for pair in pairs:
        if isinstance(pair, dict):
            clean = pair.get("clean_prompt")
            if isinstance(clean, str):
                prompts.append(clean)
    if not prompts:
        prompts = ["The capital of France is"]
    return prompts
