"""Per-family follow-up generators for the agentic research loop.

After an experiment finishes, the matching generator reads its artifacts and
emits new ``ExperimentSpec`` YAMLs that probe the most interesting findings:

* A polysemanticity SAE run → ``circuit_patching`` specs that ablate the
  decoder direction of each top-activating feature, testing whether the feature
  carries causal weight rather than just correlating with the prompts.
* An ACDC-lite run → ``activation_capture`` specs that grab raw activations at
  every surviving high-importance node, enabling downstream feature analysis.

The base ``ProposalGenerator`` is intentionally tiny so adding a fourth family
is a single class. Generators write nothing to disk; the orchestrator wraps the
specs they emit into the standard ``proposal_manifest.json`` schema.
"""

from __future__ import annotations

import json
from abc import ABC, abstractmethod
from pathlib import Path
from typing import Any


class ProposalGenerator(ABC):
    """Base class for family-specific proposal generators."""

    family: str = ""

    @abstractmethod
    def generate(self, artifact_dir: Path, *, limit: int = 5) -> list[dict[str, Any]]:
        """Return a list of proposed experiment-spec dicts (ready to YAML-dump).

        Implementations should be defensive: artifact directories may have
        partial / corrupted files, and the generator should silently skip
        unparseable artifacts rather than raise.
        """


class PolysemanticitySAEProposalGenerator(ProposalGenerator):
    """Take the top-K live features and propose a residual-stream ablation
    experiment on the hook site the SAE was trained on. The point of the
    follow-up is to verify each feature actually moves model behaviour, not
    just that it activates on a coherent prompt cluster.
    """

    family = "polysemanticity_sae"

    def generate(self, artifact_dir: Path, *, limit: int = 5) -> list[dict[str, Any]]:
        analysis_path = artifact_dir / "feature_analysis.json"
        config_path = artifact_dir / "sae_weights.safetensors.json"
        spec_path = artifact_dir / "spec.json"
        try:
            analysis = json.loads(analysis_path.read_text())
            config = json.loads(config_path.read_text())
            spec = json.loads(spec_path.read_text())
        except (OSError, json.JSONDecodeError):
            return []

        hook_site = spec.get("parameters", {}).get("hook_site", "blocks.0.hook_resid_pre")
        model = spec.get("parameters", {}).get("model", "gpt2-small")
        live_features = sorted(
            (f for f in analysis.get("features", []) if not f.get("dead", True)),
            key=lambda f: f.get("max_activation", 0.0),
            reverse=True,
        )[:limit]

        proposals: list[dict[str, Any]] = []
        for rank, feature in enumerate(live_features, start=1):
            top_prompts = feature.get("top_prompts", [])
            if len(top_prompts) < 2:
                continue
            clean_prompt = top_prompts[0]["prompt"]
            corrupted_prompt = top_prompts[-1]["prompt"]
            proposals.append(
                {
                    "name": f"sae-feature-{feature['feature_index']:04d}-causal-probe",
                    "family": "circuit_patching",
                    "backend": "transformerlens",
                    "description": (
                        f"Causal verification for SAE feature {feature['feature_index']} "
                        f"(coherence {feature.get('coherence_score', 0):.2f}, max-act "
                        f"{feature.get('max_activation', 0):.2f}). Generated by SAE "
                        f"follow-up generator from {analysis_path.name}."
                    ),
                    "parameters": {
                        "model": model,
                        "prompt_pairs": [
                            {
                                "id": f"feature-{feature['feature_index']:04d}",
                                "clean_prompt": clean_prompt,
                                "corrupted_prompt": corrupted_prompt,
                                "correct_token": _last_word_token(clean_prompt),
                                "incorrect_token": _last_word_token(corrupted_prompt),
                            }
                        ],
                        "hook_sites": [hook_site],
                        "control_hook_sites": [_mlp_control_site(hook_site)],
                        "seed": 42,
                        "rank": rank,
                        "source_feature_index": feature["feature_index"],
                        "source_sae_config": {
                            "n_features": config.get("n_features"),
                            "k": config.get("k"),
                        },
                        "artifact_policy": {
                            "retain_activation_tensors": False,
                            "write_report": True,
                        },
                    },
                }
            )
        return proposals


class ACDCLiteProposalGenerator(ProposalGenerator):
    """Take the top-K surviving ACDC nodes and propose raw activation captures
    at those hook sites so we can feed them into the SAE / cross-model pipelines.
    """

    family = "acdc_lite"

    def generate(self, artifact_dir: Path, *, limit: int = 5) -> list[dict[str, Any]]:
        circuit_path = artifact_dir / "circuit.json"
        spec_path = artifact_dir / "spec.json"
        try:
            circuit = json.loads(circuit_path.read_text())
            spec = json.loads(spec_path.read_text())
        except (OSError, json.JSONDecodeError):
            return []

        model = spec.get("parameters", {}).get("model", circuit.get("model", "gpt2-small"))
        survivors = sorted(
            (n for n in circuit.get("nodes", []) if not n.get("pruned", True)),
            key=lambda n: n.get("importance", 0.0),
            reverse=True,
        )[:limit]
        if not survivors:
            return []

        hook_sites = [_node_to_hook_site(node) for node in survivors]
        # NOTE: activation_capture is a runner parameter, not a registered family.
        # We wrap it under family=polysemanticity (matches examples/activation_capture.yaml)
        # so the generated spec passes the spec-loader's family enum check.
        return [
            {
                "name": "acdc-survivors-activation-capture",
                "family": "polysemanticity",
                "backend": "transformerlens",
                "description": (
                    f"Activation capture at the {len(hook_sites)} surviving ACDC nodes "
                    f"(faithfulness {circuit.get('faithfulness', 0):.2f}). Generated by "
                    f"ACDC follow-up generator from {circuit_path.name}."
                ),
                "parameters": {
                    "runner": "activation_capture",
                    "model_name": model,
                    "prompts": _capture_prompts_from_acdc_spec(spec),
                    "sites": hook_sites,
                    "seed": 42,
                    "source_acdc_faithfulness": circuit.get("faithfulness", 0.0),
                    "source_node_importances": [n.get("importance", 0.0) for n in survivors],
                },
            }
        ]


PROPOSAL_GENERATORS: dict[str, ProposalGenerator] = {
    "polysemanticity_sae": PolysemanticitySAEProposalGenerator(),
    "acdc_lite": ACDCLiteProposalGenerator(),
}


def _last_word_token(prompt: str) -> str:
    words = prompt.rstrip(".!?").split()
    if not words:
        return " the"
    return f" {words[-1]}"


def _mlp_control_site(hook_site: str) -> str:
    # If the SAE was trained on resid_pre, propose the MLP output as a control
    # site at the same layer — matches the existing circuit_patching convention.
    parts = hook_site.split(".")
    for _i, part in enumerate(parts):
        if part.isdigit():
            return f"blocks.{part}.mlp.hook_post"
    return "blocks.0.mlp.hook_post"


def _node_to_hook_site(node: dict[str, Any]) -> str:
    component = node.get("component")
    layer = int(node.get("layer", 0))
    if component == "mlp":
        return f"blocks.{layer}.hook_mlp_out"
    return f"blocks.{layer}.attn.hook_z"  # full z tensor; the head index is in node_id


def _capture_prompts_from_acdc_spec(spec: dict[str, Any]) -> list[str]:
    pairs = spec.get("parameters", {}).get("prompt_pairs", [])
    prompts: list[str] = []
    for pair in pairs:
        if isinstance(pair, dict):
            clean = pair.get("clean_prompt")
            if isinstance(clean, str):
                prompts.append(clean)
    if not prompts:
        prompts = ["The capital of France is"]
    return prompts
